package com.afterglowtv.app.ui.design

import androidx.compose.ui.graphics.Color

/**
 * A bundled theme identity: backgrounds, accents, semantics, text — everything
 * that gives AfterglowTV a distinct visual character.
 *
 * Themes are intentionally **not just hex swaps**: they pair backgrounds with
 * accents that have a coherent mood (cobalt slate + neon peach; pitch-black +
 * electric blue; warm ember + pink; etc.) and shift the `nowLine` and `live`
 * indicator hue together so the EPG still pops without clashing.
 *
 * Future work: extend with corner-radius scale, density factor, focus-highlight
 * style enum, and typography weight so themes diverge in dimension/density too.
 */
data class AppPalette(
    val id: String,
    val displayName: String,
    val description: String,

    // Surfaces — darkest → lightest
    val surfaceDeep: Color,
    val surfaceBase: Color,
    val surfaceCool: Color,
    val surfaceAccent: Color,

    // Accent family
    val accent: Color,
    val accentLight: Color,
    val accentMuted: Color,

    // Scrims
    val panelScrim: Color,
    val osdScrim: Color,

    // EPG / live indicator
    val nowLine: Color,
    val nowFill: Color,
    val live: Color,

    // PiP / framing
    val pipPreviewOutline: Color,
    val focusFill: Color,

    // Text
    val textPrimary: Color,
    val textSecondary: Color,
    val textTertiary: Color,
    val textDisabled: Color,

    // Semantics
    val success: Color,
    val warning: Color,
    val info: Color,

    // Lines
    val divider: Color,
    val outline: Color,
    val glowIntensity: Float = 1f,
) {
    fun glowAlpha(alpha: Float): Float = (alpha * glowIntensity).coerceIn(0f, 1f)

    companion object {
        /** Default. Cobalt slate darks, blue accent, hot-magenta now-line. Modern, neon-leaning. */
        val NeonDusk = AppPalette(
            id = "neon_dusk",
            displayName = "Neon Dusk",
            description = "Cobalt slate darks, electric blue accent, and magenta now-line.",
            surfaceDeep = Color(0xFF060A14),
            surfaceBase = Color(0xFF101A32),
            surfaceCool = Color(0xFF22355A),
            surfaceAccent = Color(0xFF314C78),
            accent = Color(0xFF4E8DFF),
            accentLight = Color(0xFFA9C8FF),
            accentMuted = Color(0x664E8DFF),
            panelScrim = Color(0xCC080B12),
            osdScrim = Color(0x99080B12),
            nowLine = Color(0xFFFF3D7F),
            nowFill = Color(0x334E8DFF),
            live = Color(0xFFFF3D7F),
            pipPreviewOutline = Color(0xFF4E8DFF),
            focusFill = Color(0x334E8DFF),
            textPrimary = Color(0xFFFFFFFF),
            textSecondary = Color(0xB3EEEEEE),
            textTertiary = Color(0x80EEEEEE),
            textDisabled = Color(0x4DEEEEEE),
            success = Color(0xFF5E9CFF),
            warning = Color(0xFFFFD166),
            info = Color(0xFFA9C8FF),
            divider = Color(0x1AFFFFFF),
            outline = Color(0x334E8DFF),
            glowIntensity = 0.35f,
        )

        /** Blue-gray steel surfaces with cool blue focus and softened chrome edges. */
        val BlueSteel = AppPalette(
            id = "blue_steel",
            displayName = "Blue Steel",
            description = "Layered blue-gray steel with cool chrome highlights and soft signal-blue edges.",
            surfaceDeep = Color(0xFF112A3C),
            surfaceBase = Color(0xFF163044),
            surfaceCool = Color(0xFF2D536A),
            surfaceAccent = Color(0xFF4C6E84),
            accent = Color(0xFF89A8BC),
            accentLight = Color(0xFFD1DEE8),
            accentMuted = Color(0x6689A8BC),
            panelScrim = Color(0xE613212B),
            osdScrim = Color(0xB313212B),
            nowLine = Color(0xFFB8CEDD),
            nowFill = Color(0x3389A8BC),
            live = Color(0xFFB8CEDD),
            pipPreviewOutline = Color(0xFFD1DEE8),
            focusFill = Color(0x3389A8BC),
            textPrimary = Color(0xFFF5FAFF),
            textSecondary = Color(0xD9D8E7F0),
            textTertiary = Color(0x99D8E7F0),
            textDisabled = Color(0x66D8E7F0),
            success = Color(0xFF9FC3D6),
            warning = Color(0xFFE8B468),
            info = Color(0xFFD1DEE8),
            divider = Color(0x2289A8BC),
            outline = Color(0x6689A8BC),
            glowIntensity = 0.35f,
        )

        /** Rachel's Sunset — pastel mint, cream, neon peach, and coral-pink glow. */
        val SunsetAurora = AppPalette(
            id = "sunset_aurora",
            displayName = "Rachel's Sunset",
            description = "I love you Rachel! Deep violet with blended neon peach, hot pink, mint teal, and girly blue sunset washes.",
            surfaceDeep = Color(0xFF17102C),
            surfaceBase = Color(0xFF0E5666),
            surfaceCool = Color(0xFFFF8A42),
            surfaceAccent = Color(0xFFFF4FA3),
            accent = Color(0xFF3152FF),
            accentLight = Color(0xFF8AA0FF),
            accentMuted = Color(0x663152FF),
            panelScrim = Color(0xD617102C),
            osdScrim = Color(0xA617102C),
            nowLine = Color(0xFFFF5FA8),
            nowFill = Color(0x333152FF),
            live = Color(0xFFFF6FB8),
            pipPreviewOutline = Color(0xFF3152FF),
            focusFill = Color(0x403152FF),
            textPrimary = Color(0xFFFFF7E9),
            textSecondary = Color(0xD9FCEADC),
            textTertiary = Color(0x99FCEADC),
            textDisabled = Color(0x66FCEADC),
            success = Color(0xFF82D8FF),
            warning = Color(0xFFFFB463),
            info = Color(0xFF82D8FF),
            divider = Color(0x22FFF7E9),
            outline = Color(0x663152FF),
            glowIntensity = 1f,
        )

        /** Calm cobalt: deep slate-blue with amber now-line. Easy on the eyes. */
        val ForestMist = AppPalette(
            id = "forest_mist",
            displayName = "Cobalt Mist",
            description = "Deep slate-blue with a calm cobalt accent. Easy on the eyes for long sessions.",
            surfaceDeep = Color(0xFF041020),
            surfaceBase = Color(0xFF0A2448),
            surfaceCool = Color(0xFF1A4270),
            surfaceAccent = Color(0xFF2B5D93),
            accent = Color(0xFF5C8DFF),
            accentLight = Color(0xFFAFC8FF),
            accentMuted = Color(0x665C8DFF),
            panelScrim = Color(0xCC07101E),
            osdScrim = Color(0x9907101E),
            nowLine = Color(0xFFFFD166),
            nowFill = Color(0x335C8DFF),
            live = Color(0xFFFFD166),
            pipPreviewOutline = Color(0xFF5C8DFF),
            focusFill = Color(0x335C8DFF),
            textPrimary = Color(0xFFF2F7FF),
            textSecondary = Color(0xCCDCE8FF),
            textTertiary = Color(0x99DCE8FF),
            textDisabled = Color(0x66DCE8FF),
            success = Color(0xFF5C8DFF),
            warning = Color(0xFFFFD166),
            info = Color(0xFFAFC8FF),
            divider = Color(0x1ADCE8FF),
            outline = Color(0x335C8DFF),
            glowIntensity = 0.35f,
        )

        /** Neon Forest — cream, mint, emerald, teal, and deep navy from the reference palette. */
        val NeonForest = AppPalette(
            id = "neon_forest",
            displayName = "Neon Forest",
            description = "Cream, mint, emerald, teal, and deep navy with a clean neon forest glow.",
            surfaceDeep = Color(0xFF08316C),
            surfaceBase = Color(0xFF0B4B73),
            surfaceCool = Color(0xFF389584),
            surfaceAccent = Color(0xFF5CDB94),
            accent = Color(0xFF8DE4AF),
            accentLight = Color(0xFFE6EDD3),
            accentMuted = Color(0x665CDB94),
            panelScrim = Color(0xD608316C),
            osdScrim = Color(0xA608316C),
            nowLine = Color(0xFFE6EDD3),
            nowFill = Color(0x335CDB94),
            live = Color(0xFF8DE4AF),
            pipPreviewOutline = Color(0xFFE6EDD3),
            focusFill = Color(0x405CDB94),
            textPrimary = Color(0xFFF7FFE9),
            textSecondary = Color(0xD9E6EDD3),
            textTertiary = Color(0x99E6EDD3),
            textDisabled = Color(0x66E6EDD3),
            success = Color(0xFF5CDB94),
            warning = Color(0xFFE6EDD3),
            info = Color(0xFF8DE4AF),
            divider = Color(0x225CDB94),
            outline = Color(0x668DE4AF),
            glowIntensity = 0.72f,
        )

        /** Skin Tone — peach, tan, copper, and warm umber from the reference palette. */
        val SkinTone = AppPalette(
            id = "skin_tone",
            displayName = "Skin Tone",
            description = "Warm peach, tan, copper, and umber with soft cream highlights.",
            surfaceDeep = Color(0xFFB36130),
            surfaceBase = Color(0xFFC87948),
            surfaceCool = Color(0xFFDB9158),
            surfaceAccent = Color(0xFFEFA968),
            accent = Color(0xFF7A3517),
            accentLight = Color(0xFFFFD2A4),
            accentMuted = Color(0x667A3517),
            panelScrim = Color(0xD62B160C),
            osdScrim = Color(0xA62B160C),
            nowLine = Color(0xFFFFE4C8),
            nowFill = Color(0x33F8BD7F),
            live = Color(0xFFF8BD7F),
            pipPreviewOutline = Color(0xFFFFD2A4),
            focusFill = Color(0x40F8BD7F),
            textPrimary = Color(0xFFFFF6EA),
            textSecondary = Color(0xD9FFE4C8),
            textTertiary = Color(0x99FFE4C8),
            textDisabled = Color(0x66FFE4C8),
            success = Color(0xFFFFC58D),
            warning = Color(0xFFFFE4C8),
            info = Color(0xFFF8BD7F),
            divider = Color(0x22FFE4C8),
            outline = Color(0x66F8BD7F),
            glowIntensity = 0.52f,
        )

        /** Mysterious Luxury — blackened teal, parchment, amber, and steel from the reference palette. */
        val MysteriousLuxury = AppPalette(
            id = "mysterious_luxury",
            displayName = "Mysterious Luxury",
            description = "Blackened teal, parchment, amber, and steel with a reserved luxury glow.",
            surfaceDeep = Color(0xFF0A1A1A),
            surfaceBase = Color(0xFF173A3A),
            surfaceCool = Color(0xFF174D4D),
            surfaceAccent = Color(0xFF25383A),
            accent = Color(0xFFE79527),
            accentLight = Color(0xFFC9C0B3),
            accentMuted = Color(0x66E79527),
            panelScrim = Color(0xD60A1A1A),
            osdScrim = Color(0xA60A1A1A),
            nowLine = Color(0xFFE79527),
            nowFill = Color(0x33174D4D),
            live = Color(0xFFE79527),
            pipPreviewOutline = Color(0xFFC9C0B3),
            focusFill = Color(0x40E79527),
            textPrimary = Color(0xFFF8F1E8),
            textSecondary = Color(0xD9C9C0B3),
            textTertiary = Color(0x99C9C0B3),
            textDisabled = Color(0x66C9C0B3),
            success = Color(0xFF8DB7B3),
            warning = Color(0xFFE79527),
            info = Color(0xFFC9C0B3),
            divider = Color(0x22C9C0B3),
            outline = Color(0x66E79527),
            glowIntensity = 0.48f,
        )

        /** Joyful — coral, blush, cream, mint, and turquoise from the reference palette. */
        val Joyful = AppPalette(
            id = "joyful",
            displayName = "Joyful",
            description = "Coral, blush pink, cream, mint, and turquoise with bright friendly contrast.",
            surfaceDeep = Color(0xFF72BCA3),
            surfaceBase = Color(0xFF8ED0BE),
            surfaceCool = Color(0xFFF0E7DA),
            surfaceAccent = Color(0xFFF6CAE0),
            accent = Color(0xFF2DA3BB),
            accentLight = Color(0xFFF26F49),
            accentMuted = Color(0x662DA3BB),
            panelScrim = Color(0xCC174A55),
            osdScrim = Color(0x99174A55),
            nowLine = Color(0xFFF26F49),
            nowFill = Color(0x332DA3BB),
            live = Color(0xFFF26F49),
            pipPreviewOutline = Color(0xFF2DA3BB),
            focusFill = Color(0x402DA3BB),
            textPrimary = Color(0xFF123840),
            textSecondary = Color(0xFF315F68),
            textTertiary = Color(0x99315F68),
            textDisabled = Color(0x66315F68),
            success = Color(0xFF2DA3BB),
            warning = Color(0xFFF26F49),
            info = Color(0xFF2DA3BB),
            divider = Color(0x22315F68),
            outline = Color(0x662DA3BB),
            glowIntensity = 0.65f,
        )

        /** Earthy — clay, deep sage, pale blue-gray, cream, and blush from the reference palette. */
        val Earthy = AppPalette(
            id = "earthy",
            displayName = "Earthy",
            description = "Clay, deep sage, pale blue-gray, cream, and blush with grounded calm contrast.",
            surfaceDeep = Color(0xFF476060),
            surfaceBase = Color(0xFF588F86),
            surfaceCool = Color(0xFFC4D0D3),
            surfaceAccent = Color(0xFFD09670),
            accent = Color(0xFF304D4D),
            accentLight = Color(0xFFEEC5BA),
            accentMuted = Color(0x66304D4D),
            panelScrim = Color(0xD62A3C3C),
            osdScrim = Color(0xA62A3C3C),
            nowLine = Color(0xFFEEC5BA),
            nowFill = Color(0x3358BF86),
            live = Color(0xFFD09670),
            pipPreviewOutline = Color(0xFFEEC5BA),
            focusFill = Color(0x4058BF86),
            textPrimary = Color(0xFFF7F2EE),
            textSecondary = Color(0xD9ECE8EA),
            textTertiary = Color(0x99ECE8EA),
            textDisabled = Color(0x66ECE8EA),
            success = Color(0xFF58BF86),
            warning = Color(0xFFD09670),
            info = Color(0xFFC4D0D3),
            divider = Color(0x22ECE8EA),
            outline = Color(0x66EEC5BA),
            glowIntensity = 0.42f,
        )

        /** Autumn Fall — honey, olive-brown, taupe, umber, and espresso from the reference palette. */
        val AutumnFall = AppPalette(
            id = "autumn_fall",
            displayName = "Autumn Fall",
            description = "Honey, olive-brown, taupe, umber, and espresso with a warm fall glow.",
            surfaceDeep = Color(0xFF543C2B),
            surfaceBase = Color(0xFF886349),
            surfaceCool = Color(0xFFAB9379),
            surfaceAccent = Color(0xFFA47E42),
            accent = Color(0xFFDB9D57),
            accentLight = Color(0xFFFFE2BD),
            accentMuted = Color(0x66DB9D57),
            panelScrim = Color(0xD6211710),
            osdScrim = Color(0xA6211710),
            nowLine = Color(0xFFDB9D57),
            nowFill = Color(0x33A47E42),
            live = Color(0xFFFFC07A),
            pipPreviewOutline = Color(0xFFDB9D57),
            focusFill = Color(0x40DB9D57),
            textPrimary = Color(0xFFFFF3E2),
            textSecondary = Color(0xD9F2DEC4),
            textTertiary = Color(0x99F2DEC4),
            textDisabled = Color(0x66F2DEC4),
            success = Color(0xFFD1B27C),
            warning = Color(0xFFDB9D57),
            info = Color(0xFFFFE2BD),
            divider = Color(0x22F2DEC4),
            outline = Color(0x66DB9D57),
            glowIntensity = 0.45f,
        )

        /** Nordic Calm — sage, oat, snow, pale blue, and slate from the reference palette. */
        val NordicCalm = AppPalette(
            id = "nordic_calm",
            displayName = "Nordic Calm",
            description = "Sage, oat, snow, pale blue, and slate with soft Nordic contrast.",
            surfaceDeep = Color(0xFF6D7D8B),
            surfaceBase = Color(0xFF99AED0),
            surfaceCool = Color(0xFFDDE7C8),
            surfaceAccent = Color(0xFFBBD0B3),
            accent = Color(0xFF3F5F86),
            accentLight = Color(0xFFF4F2EE),
            accentMuted = Color(0x663F5F86),
            panelScrim = Color(0xD62F4459),
            osdScrim = Color(0xA62F4459),
            nowLine = Color(0xFFF4F2EE),
            nowFill = Color(0x3399AED0),
            live = Color(0xFFDDE7C8),
            pipPreviewOutline = Color(0xFFF4F2EE),
            focusFill = Color(0x4099AED0),
            textPrimary = Color(0xFFF8FAF4),
            textSecondary = Color(0xD9E8EEF2),
            textTertiary = Color(0x99E8EEF2),
            textDisabled = Color(0x66E8EEF2),
            success = Color(0xFFBBD0B3),
            warning = Color(0xFFDDE7C8),
            info = Color(0xFF99AED0),
            divider = Color(0x22F4F2EE),
            outline = Color(0x66F4F2EE),
            glowIntensity = 0.35f,
        )

        /** Red Orange Sky — saturated red, coral, orange, and wine from the reference palette. */
        val RedOrangeSky = AppPalette(
            id = "red_orange_sky",
            displayName = "Red Orange Sky",
            description = "Saturated red, coral, orange, and wine sunset heat.",
            surfaceDeep = Color(0xFFBA3C4D),
            surfaceBase = Color(0xFFCA3C50),
            surfaceCool = Color(0xFFDC2C41),
            surfaceAccent = Color(0xFFF44342),
            accent = Color(0xFFF96C3C),
            accentLight = Color(0xFFFFB044),
            accentMuted = Color(0x66F96C3C),
            panelScrim = Color(0xD6331019),
            osdScrim = Color(0xA6331019),
            nowLine = Color(0xFFFFB044),
            nowFill = Color(0x33F96C3C),
            live = Color(0xFFF44342),
            pipPreviewOutline = Color(0xFFFFB044),
            focusFill = Color(0x40F96C3C),
            textPrimary = Color(0xFFFFF3E8),
            textSecondary = Color(0xD9FFE0D4),
            textTertiary = Color(0x99FFE0D4),
            textDisabled = Color(0x66FFE0D4),
            success = Color(0xFFFF9C6E),
            warning = Color(0xFFFFB044),
            info = Color(0xFFFFD0B8),
            divider = Color(0x22FFE0D4),
            outline = Color(0x66F96C3C),
            glowIntensity = 0.82f,
        )

        /** Solar Afterglow — orange sun, gold, brick, deep umber, and burnt orange. */
        val SolarAfterglow = AppPalette(
            id = "solar_afterglow",
            displayName = "Solar Afterglow",
            description = "Orange sun, gold, brick, deep umber, and burnt orange.",
            surfaceDeep = Color(0xFF523423),
            surfaceBase = Color(0xFF913518),
            surfaceCool = Color(0xFFC45513),
            surfaceAccent = Color(0xFFED7205),
            accent = Color(0xFFFBBC07),
            accentLight = Color(0xFFFFD36A),
            accentMuted = Color(0x66FBBC07),
            panelScrim = Color(0xD623130B),
            osdScrim = Color(0xA623130B),
            nowLine = Color(0xFFFBBC07),
            nowFill = Color(0x33ED7205),
            live = Color(0xFFED7205),
            pipPreviewOutline = Color(0xFFFBBC07),
            focusFill = Color(0x40ED7205),
            textPrimary = Color(0xFFFFF4D6),
            textSecondary = Color(0xD9FFE3B0),
            textTertiary = Color(0x99FFE3B0),
            textDisabled = Color(0x66FFE3B0),
            success = Color(0xFFE8A33A),
            warning = Color(0xFFFBBC07),
            info = Color(0xFFFFD36A),
            divider = Color(0x22FFE3B0),
            outline = Color(0x66FBBC07),
            glowIntensity = 0.78f,
        )

        /** Sea Horizon — beach umber, near-black, dark sage, charcoal, and ember orange. */
        val SeaHorizon = AppPalette(
            id = "sea_horizon",
            displayName = "Sea Horizon",
            description = "Beach umber, near-black, dark sage, charcoal, and ember orange.",
            surfaceDeep = Color(0xFF17191B),
            surfaceBase = Color(0xFF2F2E2C),
            surfaceCool = Color(0xFF3B4E40),
            surfaceAccent = Color(0xFF846146),
            accent = Color(0xFFAE3B13),
            accentLight = Color(0xFFE28C4E),
            accentMuted = Color(0x66AE3B13),
            panelScrim = Color(0xD617191B),
            osdScrim = Color(0xA617191B),
            nowLine = Color(0xFFE28C4E),
            nowFill = Color(0x333B4E40),
            live = Color(0xFFAE3B13),
            pipPreviewOutline = Color(0xFFE28C4E),
            focusFill = Color(0x40AE3B13),
            textPrimary = Color(0xFFFFF0E3),
            textSecondary = Color(0xD9D9C7B7),
            textTertiary = Color(0x99D9C7B7),
            textDisabled = Color(0x66D9C7B7),
            success = Color(0xFF8CA68E),
            warning = Color(0xFFE28C4E),
            info = Color(0xFFB9C2BA),
            divider = Color(0x22D9C7B7),
            outline = Color(0x66AE3B13),
            glowIntensity = 0.44f,
        )

        /** Red Sky Morning — red dawn, sand, steel blue, midnight, and muted olive. */
        val RedSkyMorning = AppPalette(
            id = "red_sky_morning",
            displayName = "Red Sky Morning",
            description = "Red dawn, sand, steel blue, midnight, and muted olive.",
            surfaceDeep = Color(0xFF23233B),
            surfaceBase = Color(0xFF3F746D),
            surfaceCool = Color(0xFFA4A484),
            surfaceAccent = Color(0xFFDFBD80),
            accent = Color(0xFFDC443C),
            accentLight = Color(0xFFFFD78F),
            accentMuted = Color(0x66DC443C),
            panelScrim = Color(0xD61E2033),
            osdScrim = Color(0xA61E2033),
            nowLine = Color(0xFFDC443C),
            nowFill = Color(0x333F746D),
            live = Color(0xFFDC443C),
            pipPreviewOutline = Color(0xFFDFBD80),
            focusFill = Color(0x40DC443C),
            textPrimary = Color(0xFFFFF3DC),
            textSecondary = Color(0xD9EADDBF),
            textTertiary = Color(0x99EADDBF),
            textDisabled = Color(0x66EADDBF),
            success = Color(0xFFA4A484),
            warning = Color(0xFFDFBD80),
            info = Color(0xFF9CB8C8),
            divider = Color(0x22EADDBF),
            outline = Color(0x66DFBD80),
            glowIntensity = 0.55f,
        )

        /** Mountain Afterglow — rust, ink navy, smoky violet, blue slate, and clay red. */
        val MountainAfterglow = AppPalette(
            id = "mountain_afterglow",
            displayName = "Mountain Afterglow",
            description = "Rust, ink navy, smoky violet, blue slate, and clay red.",
            surfaceDeep = Color(0xFF141B24),
            surfaceBase = Color(0xFF223444),
            surfaceCool = Color(0xFF4F3654),
            surfaceAccent = Color(0xFF9C4A44),
            accent = Color(0xFF95382C),
            accentLight = Color(0xFFE67D4D),
            accentMuted = Color(0x6695382C),
            panelScrim = Color(0xD6141B24),
            osdScrim = Color(0xA6141B24),
            nowLine = Color(0xFFE67D4D),
            nowFill = Color(0x334F3654),
            live = Color(0xFFE67D4D),
            pipPreviewOutline = Color(0xFF9C4A44),
            focusFill = Color(0x4095382C),
            textPrimary = Color(0xFFFFEEE6),
            textSecondary = Color(0xD9E6C9C0),
            textTertiary = Color(0x99E6C9C0),
            textDisabled = Color(0x66E6C9C0),
            success = Color(0xFF8DA7BC),
            warning = Color(0xFFE67D4D),
            info = Color(0xFFC19AC8),
            divider = Color(0x22E6C9C0),
            outline = Color(0x669C4A44),
            glowIntensity = 0.5f,
        )

        /** Tokyo Sunset — coral, warm yellow, electric blue, and violet. */
        val TokyoSunset = AppPalette(
            id = "tokyo_sunset",
            displayName = "Tokyo Sunset",
            description = "Coral, warm yellow, electric blue, and violet in a punchy poster palette.",
            surfaceDeep = Color(0xFF1E2541),
            surfaceBase = Color(0xFF3A86FF),
            surfaceCool = Color(0xFFFFD166),
            surfaceAccent = Color(0xFFFF7E67),
            accent = Color(0xFF8338EC),
            accentLight = Color(0xFFFFD166),
            accentMuted = Color(0x668338EC),
            panelScrim = Color(0xD61E2541),
            osdScrim = Color(0xA61E2541),
            nowLine = Color(0xFFFF7E67),
            nowFill = Color(0x333A86FF),
            live = Color(0xFFFF7E67),
            pipPreviewOutline = Color(0xFFFFD166),
            focusFill = Color(0x408338EC),
            textPrimary = Color(0xFFFFFFFF),
            textSecondary = Color(0xD9F4ECFF),
            textTertiary = Color(0x99F4ECFF),
            textDisabled = Color(0x66F4ECFF),
            success = Color(0xFF3A86FF),
            warning = Color(0xFFFFD166),
            info = Color(0xFFB48CFF),
            divider = Color(0x22FFFFFF),
            outline = Color(0x668338EC),
            glowIntensity = 0.85f,
        )

        /** Windfarm Sunset — peach, apricot, orange, amber, and black-brown. */
        val WindfarmSunset = AppPalette(
            id = "windfarm_sunset",
            displayName = "Windfarm Sunset",
            description = "Peach, apricot, orange, amber, and black-brown evening contrast.",
            surfaceDeep = Color(0xFF221416),
            surfaceBase = Color(0xFF702F18),
            surfaceCool = Color(0xFFF1830E),
            surfaceAccent = Color(0xFFF3982E),
            accent = Color(0xFFEAB182),
            accentLight = Color(0xFFEF9F58),
            accentMuted = Color(0x66EAB182),
            panelScrim = Color(0xD6221416),
            osdScrim = Color(0xA6221416),
            nowLine = Color(0xFFF3982E),
            nowFill = Color(0x33F1830E),
            live = Color(0xFFF1830E),
            pipPreviewOutline = Color(0xFFEF9F58),
            focusFill = Color(0x40EAB182),
            textPrimary = Color(0xFFFFF1E5),
            textSecondary = Color(0xD9F8D8C0),
            textTertiary = Color(0x99F8D8C0),
            textDisabled = Color(0x66F8D8C0),
            success = Color(0xFFEAB182),
            warning = Color(0xFFF3982E),
            info = Color(0xFFEF9F58),
            divider = Color(0x22F8D8C0),
            outline = Color(0x66EF9F58),
            glowIntensity = 0.55f,
        )

        /** City Afterglow — gray green, wine charcoal, night slate, gold, and brick. */
        val CityAfterglow = AppPalette(
            id = "city_afterglow",
            displayName = "City Afterglow",
            description = "Gray green, wine charcoal, night slate, gold, and brick.",
            surfaceDeep = Color(0xFF151C23),
            surfaceBase = Color(0xFF39292A),
            surfaceCool = Color(0xFF596361),
            surfaceAccent = Color(0xFF702F18),
            accent = Color(0xFFE7AE37),
            accentLight = Color(0xFFFFD36A),
            accentMuted = Color(0x66E7AE37),
            panelScrim = Color(0xD6151C23),
            osdScrim = Color(0xA6151C23),
            nowLine = Color(0xFFE7AE37),
            nowFill = Color(0x33596361),
            live = Color(0xFFE7AE37),
            pipPreviewOutline = Color(0xFFE7AE37),
            focusFill = Color(0x40E7AE37),
            textPrimary = Color(0xFFFFF4D8),
            textSecondary = Color(0xD9DED5C8),
            textTertiary = Color(0x99DED5C8),
            textDisabled = Color(0x66DED5C8),
            success = Color(0xFF9AA59F),
            warning = Color(0xFFE7AE37),
            info = Color(0xFFFFD36A),
            divider = Color(0x22DED5C8),
            outline = Color(0x66E7AE37),
            glowIntensity = 0.45f,
        )

        /** Golden Ocean — bronze, amber, gold, umber, olive, and deep brown from the large swatch palette. */
        val GoldenOcean = AppPalette(
            id = "golden_ocean",
            displayName = "Golden Ocean",
            description = "Bronze, amber, gold, umber, olive, and deep brown sunset range.",
            surfaceDeep = Color(0xFF2D1C0C),
            surfaceBase = Color(0xFF533416),
            surfaceCool = Color(0xFF7A461A),
            surfaceAccent = Color(0xFFB5893F),
            accent = Color(0xFFDA892A),
            accentLight = Color(0xFFE3BA56),
            accentMuted = Color(0x66DA892A),
            panelScrim = Color(0xD62D1C0C),
            osdScrim = Color(0xA62D1C0C),
            nowLine = Color(0xFFE3BA56),
            nowFill = Color(0x33DA892A),
            live = Color(0xFFD75318),
            pipPreviewOutline = Color(0xFFE3BA56),
            focusFill = Color(0x40DA892A),
            textPrimary = Color(0xFFFFF0C9),
            textSecondary = Color(0xD9E8D0A0),
            textTertiary = Color(0x99E8D0A0),
            textDisabled = Color(0x66E8D0A0),
            success = Color(0xFF7E5F2D),
            warning = Color(0xFFE3BA56),
            info = Color(0xFFB5893F),
            divider = Color(0x22E8D0A0),
            outline = Color(0x66E3BA56),
            glowIntensity = 0.5f,
        )

        /** Burning Sky — bright yellow, brick red, hot orange, flame orange, and mustard. */
        val BurningSky = AppPalette(
            id = "burning_sky",
            displayName = "Burning Sky",
            description = "Bright yellow, brick red, hot orange, flame orange, and mustard.",
            surfaceDeep = Color(0xFFAD3304),
            surfaceBase = Color(0xFFEC5C04),
            surfaceCool = Color(0xFFFBA52B),
            surfaceAccent = Color(0xFFD49C0C),
            accent = Color(0xFFFBC540),
            accentLight = Color(0xFFFFE082),
            accentMuted = Color(0x66FBC540),
            panelScrim = Color(0xD6270B02),
            osdScrim = Color(0xA6270B02),
            nowLine = Color(0xFFFBC540),
            nowFill = Color(0x33EC5C04),
            live = Color(0xFFEC5C04),
            pipPreviewOutline = Color(0xFFFBC540),
            focusFill = Color(0x40FBC540),
            textPrimary = Color(0xFFFFF6D6),
            textSecondary = Color(0xD9FFE2A3),
            textTertiary = Color(0x99FFE2A3),
            textDisabled = Color(0x66FFE2A3),
            success = Color(0xFFD49C0C),
            warning = Color(0xFFFBC540),
            info = Color(0xFFFFE082),
            divider = Color(0x22FFE2A3),
            outline = Color(0x66FBC540),
            glowIntensity = 0.8f,
        )

        /** Minimal mono: near-black + clean whites + grey accents. For minimalists. */
        val PureOnyx = AppPalette(
            id = "pure_onyx",
            displayName = "Pure Onyx",
            description = "Near-black with clean whites and minimal grey accents. Minimalist, content-first.",
            surfaceDeep = Color(0xFF050505),
            surfaceBase = Color(0xFF0F0F0F),
            surfaceCool = Color(0xFF1A1A1A),
            surfaceAccent = Color(0xFF252525),
            accent = Color(0xFFE8E8E8),
            accentLight = Color(0xFFFFFFFF),
            accentMuted = Color(0x66E8E8E8),
            panelScrim = Color(0xE6000000),
            osdScrim = Color(0xB3000000),
            nowLine = Color(0xFFE5484D),
            nowFill = Color(0x33FFFFFF),
            live = Color(0xFFE5484D),
            pipPreviewOutline = Color(0xFFE8E8E8),
            focusFill = Color(0x33FFFFFF),
            textPrimary = Color(0xFFFFFFFF),
            textSecondary = Color(0xCCFFFFFF),
            textTertiary = Color(0x99FFFFFF),
            textDisabled = Color(0x66FFFFFF),
            success = Color(0xFF7FA7FF),
            warning = Color(0xFFFFD166),
            info = Color(0xFFE8E8E8),
            divider = Color(0x1AFFFFFF),
            outline = Color(0x33FFFFFF),
            glowIntensity = 0.35f,
        )

        /** Classic blue IPTV palette. */
        val ClassicBlue = AppPalette(
            id = "classic_blue",
            displayName = "Classic Blue",
            description = "Layered navy and broadcast blue chrome with crisp red live markers and restrained glow.",
            surfaceDeep = Color(0xFF04162E),
            surfaceBase = Color(0xFF092B56),
            surfaceCool = Color(0xFF14508B),
            surfaceAccent = Color(0xFF2372B7),
            accent = Color(0xFF2196F3),
            accentLight = Color(0xFF90CAF9),
            accentMuted = Color(0x662196F3),
            panelScrim = Color(0xD6061B33),
            osdScrim = Color(0xA6061B33),
            nowLine = Color(0xFFF44336),
            nowFill = Color(0x602196F3),
            live = Color(0xFFF44336),
            pipPreviewOutline = Color(0xFF2196F3),
            focusFill = Color(0x402196F3),
            textPrimary = Color(0xFFF4FAFF),
            textSecondary = Color(0xCCD4E9FF),
            textTertiary = Color(0x99D4E9FF),
            textDisabled = Color(0x66D4E9FF),
            success = Color(0xFF4FD39A),
            warning = Color(0xFFFFC107),
            info = Color(0xFF2DAAE2),
            divider = Color(0x1AF4F8FF),
            outline = Color(0x264C6D95),
            glowIntensity = 0.35f,
        )

        /** Synthwave — black laser grid with hot pink and yellow. Distinct from Afterglow. */
        val Synthwave = AppPalette(
            id = "synthwave",
            displayName = "Synthwave",
            description = "Black laser grid with hot pink, sun yellow, and cobalt edge light.",
            surfaceDeep = Color(0xFF02020A),
            surfaceBase = Color(0xFF150824),
            surfaceCool = Color(0xFF231B55),
            surfaceAccent = Color(0xFF203C7A),
            accent = Color(0xFFFF2F88),
            accentLight = Color(0xFFFFD447),
            accentMuted = Color(0x66FF2A6D),
            panelScrim = Color(0xCC020305),
            osdScrim = Color(0x99020305),
            nowLine = Color(0xFFFFD447),
            nowFill = Color(0x33FF2F88),
            live = Color(0xFFFFD447),
            pipPreviewOutline = Color(0xFF4E8DFF),
            focusFill = Color(0x33FF2F88),
            textPrimary = Color(0xFFFFF2F8),
            textSecondary = Color(0xCCD7E4FF),
            textTertiary = Color(0x99D7E4FF),
            textDisabled = Color(0x66D7E4FF),
            success = Color(0xFF4E8DFF),
            warning = Color(0xFFFFD447),
            info = Color(0xFFFF6EA8),
            divider = Color(0x22D7E4FF),
            outline = Color(0x444E8DFF),
            glowIntensity = 0.35f,
        )

        /** Vaporwave — warm chrome sunset with no purple-family base. */
        val Vaporwave = AppPalette(
            id = "vaporwave",
            displayName = "Vaporwave",
            description = "Chrome charcoal with neon sunset orange, hot pink, and gold.",
            surfaceDeep = Color(0xFF0C0A0C),
            surfaceBase = Color(0xFF2A1622),
            surfaceCool = Color(0xFF4A2B2A),
            surfaceAccent = Color(0xFF6B4933),
            accent = Color(0xFFFF7A38),
            accentLight = Color(0xFFFFC44A),
            accentMuted = Color(0x66FF7A38),
            panelScrim = Color(0xCC12110F),
            osdScrim = Color(0x9912110F),
            nowLine = Color(0xFFFF3DAF),
            nowFill = Color(0x33FF7A38),
            live = Color(0xFFFF3DAF),
            pipPreviewOutline = Color(0xFFFF477E),
            focusFill = Color(0x40FF7A38),
            textPrimary = Color(0xFFFFF7E8),
            textSecondary = Color(0xCCFFE8C7),
            textTertiary = Color(0x99FFE8C7),
            textDisabled = Color(0x66FFE8C7),
            success = Color(0xFF4E8DFF),
            warning = Color(0xFFFFC44A),
            info = Color(0xFFFFB47A),
            divider = Color(0x22FFE8C7),
            outline = Color(0x40FF7A38),
            glowIntensity = 0.35f,
        )

        /** Afterglow Gray — direct port of the user's favorite YTAfterglow preset.
         *  Charcoal-monochrome: pure grayscale luminance steps, no chroma. Pure
         *  white accent on `#2E2E2E` body. The Lite-inspired "soft white controls
         *  on charcoal" look from the iOS YouTube tweak, applied to a TV grid. */
        val AfterglowGray = AppPalette(
            id = "afterglow_gray",
            displayName = "Afterglow Gray",
            description = "Charcoal monochrome — pure white controls on `#2E2E2E` body. The Lite-inspired YT favorite.",
            surfaceDeep = Color(0xFF242424),         // YTAG-inspired charcoal
            surfaceBase = Color(0xFF353535),
            surfaceCool = Color(0xFF505050),
            surfaceAccent = Color(0xFF6A6A6A),
            accent = Color(0xFFFFFFFF),              // YTAG accent — pure white
            accentLight = Color(0xFFFAFAFA),         // YTAG overlay
            accentMuted = Color(0x66FFFFFF),
            panelScrim = Color(0xCC1F1F1F),
            osdScrim = Color(0x991F1F1F),
            nowLine = Color(0xFFFFFFFF),             // pure-white now-line pops on `#2E2E2E`
            nowFill = Color(0x33FFFFFF),
            live = Color(0xFFFFFFFF),
            pipPreviewOutline = Color(0xFFFFFFFF),
            focusFill = Color(0x33FFFFFF),
            textPrimary = Color(0xFFF5F5F5),         // YTAG textP (white 0.96)
            textSecondary = Color(0xFFC7C7C7),       // YTAG textS (white 0.78)
            textTertiary = Color(0x99F5F5F5),
            textDisabled = Color(0x66F5F5F5),
            success = Color(0xFFFFFFFF),             // monochrome keeps semantics in luminance only
            warning = Color(0xFFC7C7C7),
            info = Color(0xFFEBEBEB),                // YTAG seekBar
            divider = Color(0x22FFFFFF),
            outline = Color(0x33FFFFFF),
        )

        /** Afterglow Dark 2 — default first-run palette. */
        val AfterglowSunset = AppPalette(
            id = "afterglow_sunset",
            displayName = "Afterglow Dark 2",
            description = "Cobalt-black with neon orange and hot-pink Afterglow accents.",
            surfaceDeep = Color(0xFF050914),
            surfaceBase = Color(0xFF0D1424),
            surfaceCool = Color(0xFF172238),
            surfaceAccent = Color(0xFF263A5A),
            accent = Color(0xFFFF7A18),
            accentLight = Color(0xFFFFB15F),
            accentMuted = Color(0x66FF7A18),
            panelScrim = Color(0xCC050914),
            osdScrim = Color(0x99050914),
            nowLine = Color(0xFFFF2D7A),
            nowFill = Color(0x33FF7A18),
            live = Color(0xFFFF2D7A),
            pipPreviewOutline = Color(0xFFFF7A18),
            focusFill = Color(0x40FF7A18),
            textPrimary = Color(0xFFFFF4D2),
            textSecondary = Color(0xD9FFC285),
            textTertiary = Color(0x99FFC285),
            textDisabled = Color(0x66FFC285),
            success = Color(0xFFFFB15F),
            warning = Color(0xFFFF7A18),
            info = Color(0xFFFF7DB0),
            divider = Color(0x22FFE4D8),
            outline = Color(0x55FF7A18),
        )

        /** Afterglow 1 — cool graphite with blue-steel controls. */
        val Afterglow1 = AppPalette(
            id = "afterglow_1",
            displayName = "Afterglow Dark 1",
            description = "Graphite-black surfaces with blue-steel focus and frosted signal-blue live markers.",
            surfaceDeep = Color(0xFF05080B),
            surfaceBase = Color(0xFF0D141A),
            surfaceCool = Color(0xFF16212A),
            surfaceAccent = Color(0xFF263646),
            accent = Color(0xFF6F8FA8),
            accentLight = Color(0xFFB7C9D8),
            accentMuted = Color(0x666F8FA8),
            panelScrim = Color(0xD605080B),
            osdScrim = Color(0x9905080B),
            nowLine = Color(0xFF9DB8CC),
            nowFill = Color(0x336F8FA8),
            live = Color(0xFF9DB8CC),
            pipPreviewOutline = Color(0xFFB7C9D8),
            focusFill = Color(0x406F8FA8),
            textPrimary = Color(0xFFDCEEFF),
            textSecondary = Color(0xD9AFC7D8),
            textTertiary = Color(0x99AFC7D8),
            textDisabled = Color(0x66AFC7D8),
            success = Color(0xFF8FB2CC),
            warning = Color(0xFFE4B66B),
            info = Color(0xFFB7C9D8),
            divider = Color(0x225A748A),
            outline = Color(0x556F8FA8),
        )

        /** Afterglow 3 — deep violet glass with magenta energy. */
        val Afterglow3 = AppPalette(
            id = "afterglow_3",
            displayName = "Afterglow Dark 3",
            description = "Black-violet surfaces with electric purple focus and magenta live edge.",
            surfaceDeep = Color(0xFF0A050F),
            surfaceBase = Color(0xFF150B20),
            surfaceCool = Color(0xFF241333),
            surfaceAccent = Color(0xFF3A2052),
            accent = Color(0xFFB56BFF),
            accentLight = Color(0xFFD8B8FF),
            accentMuted = Color(0x66B56BFF),
            panelScrim = Color(0xD60A050F),
            osdScrim = Color(0x990A050F),
            nowLine = Color(0xFFFF62C7),
            nowFill = Color(0x33B56BFF),
            live = Color(0xFFFF62C7),
            pipPreviewOutline = Color(0xFFD8B8FF),
            focusFill = Color(0x40B56BFF),
            textPrimary = Color(0xFFF0E4FF),
            textSecondary = Color(0xD9C8A7FF),
            textTertiary = Color(0x99C8A7FF),
            textDisabled = Color(0x66C8A7FF),
            success = Color(0xFFD8B8FF),
            warning = Color(0xFFFFC06D),
            info = Color(0xFFFF8AD7),
            divider = Color(0x22D8C7E8),
            outline = Color(0x55B56BFF),
        )

        /** Afterglow 4 — red-black ember with gold signal color. */
        val Afterglow4 = AppPalette(
            id = "afterglow_4",
            displayName = "Afterglow Dark 4",
            description = "Near-black oxblood surfaces with ember-red focus and warm gold live markers.",
            surfaceDeep = Color(0xFF080303),
            surfaceBase = Color(0xFF170909),
            surfaceCool = Color(0xFF261111),
            surfaceAccent = Color(0xFF3F1B16),
            accent = Color(0xFFFF4D36),
            accentLight = Color(0xFFFF9A76),
            accentMuted = Color(0x66FF4D36),
            panelScrim = Color(0xE6080303),
            osdScrim = Color(0xAA080303),
            nowLine = Color(0xFFFFC857),
            nowFill = Color(0x33FF4D36),
            live = Color(0xFFFFC857),
            pipPreviewOutline = Color(0xFFFF9A76),
            focusFill = Color(0x45FF4D36),
            textPrimary = Color(0xFFFFD1BE),
            textSecondary = Color(0xD9FF9F85),
            textTertiary = Color(0x99FF9F85),
            textDisabled = Color(0x66FF9F85),
            success = Color(0xFFFFC857),
            warning = Color(0xFFFF9A76),
            info = Color(0xFFFFD97F),
            divider = Color(0x22E8B6A8),
            outline = Color(0x55FF4D36),
        )

        // ── Light palettes ───────────────────────────────────────────
        // The light themes are intentionally not white themes. They use
        // smoky, sunset-tinted surfaces with dark text so TV menus keep real
        // contrast instead of turning into a bright flat sheet.

        /** Afterglow Gray Light — pale charcoal monochrome (the inverse of
         *  Afterglow Gray Dark). Bright surfaces, dark controls. */
        val AfterglowGrayLight = AppPalette(
            id = "afterglow_gray_light",
            displayName = "Afterglow Gray Light",
            description = "Soft ash monochrome — dark controls on a muted gray body.",
            surfaceDeep = Color(0xFFB8B8B8),
            surfaceBase = Color(0xFFD0D0D0),
            surfaceCool = Color(0xFFEAEAEA),
            surfaceAccent = Color(0xFFA2A2A2),
            accent = Color(0xFF202020),
            accentLight = Color(0xFF464646),
            accentMuted = Color(0x66333333),
            panelScrim = Color(0xCC1F1F1F),
            osdScrim = Color(0x991F1F1F),
            nowLine = Color(0xFF2C2C2C),
            nowFill = Color(0x33333333),
            live = Color(0xFF202020),
            pipPreviewOutline = Color(0xFF202020),
            focusFill = Color(0x33333333),
            textPrimary = Color(0xFF111111),
            textSecondary = Color(0xFF3D3D3D),
            textTertiary = Color(0x993D3D3D),
            textDisabled = Color(0x663D3D3D),
            success = Color(0xFF202020),
            warning = Color(0xFF4A4A4A),
            info = Color(0xFF2C2C2C),
            divider = Color(0x22000000),
            outline = Color(0x33333333),
        )

        /** Afterglow Labs — website-inspired peach/orange/pink wash with deep violet controls. */
        val AfterglowLabs = AppPalette(
            id = "afterglow_labs",
            displayName = "Afterglow Labs",
            description = "Afterglow Labs website wash: peach, orange, and pink glow with deep violet controls.",
            surfaceDeep = Color(0xFFFFAD4F),
            surfaceBase = Color(0xFFFFD8B8),
            surfaceCool = Color(0xFFFF8A5F),
            surfaceAccent = Color(0xFFFF5D9A),
            accent = Color(0xFF111F48),
            accentLight = Color(0xFF6F35D8),
            accentMuted = Color(0x66111F48),
            panelScrim = Color(0xCC111F48),
            osdScrim = Color(0x99111F48),
            nowLine = Color(0xFF2B1855),
            nowFill = Color(0x33111F48),
            live = Color(0xFF2B1855),
            pipPreviewOutline = Color(0xFF6F35D8),
            focusFill = Color(0x40111F48),
            textPrimary = Color(0xFF0E1E3F),
            textSecondary = Color(0xFF4E4566),
            textTertiary = Color(0x995E526F),
            textDisabled = Color(0x665E526F),
            success = Color(0xFF263D7E),
            warning = Color(0xFF6E3D00),
            info = Color(0xFF4C2EA5),
            divider = Color(0x556F35D8),
            outline = Color(0xFF6F35D8),
            glowIntensity = 1f,
        )

        /** Afterglow Light 1 — smoky warm gray, orange-pink glow, no whiteout. */
        val AfterglowLight1 = AppPalette(
            id = "afterglow_light_1",
            displayName = "Afterglow Light 1",
            description = "Smoky warm gray glass with orange controls, pink live glow, and medium mint highlights.",
            surfaceDeep = Color(0xFFBDAFA7),
            surfaceBase = Color(0xFFDCC2B4),
            surfaceCool = Color(0xFFF0DED3),
            surfaceAccent = Color(0xFFB79B91),
            accent = Color(0xFF9A3B1D),
            accentLight = Color(0xFF2BAE66),
            accentMuted = Color(0x669A3B1D),
            panelScrim = Color(0xCC1E2025),
            osdScrim = Color(0x991E2025),
            nowLine = Color(0xFFB82362),
            nowFill = Color(0x339A3B1D),
            live = Color(0xFFB82362),
            pipPreviewOutline = Color(0xFF9A3B1D),
            focusFill = Color(0x339A3B1D),
            textPrimary = Color(0xFF2B1830),
            textSecondary = Color(0xFF623343),
            textTertiary = Color(0x99623343),
            textDisabled = Color(0x66623343),
            success = Color(0xFF2BAE66),
            warning = Color(0xFF9A3B1D),
            info = Color(0xFF7A2754),
            divider = Color(0x22211827),
            outline = Color(0x409A3B1D),
        )

        /** Afterglow Light 2 — dim apricot sunset, closest light cousin to Dark 2. */
        val AfterglowLight2 = AppPalette(
            id = "afterglow_light_2",
            displayName = "Afterglow Light 2",
            description = "Dim apricot surfaces with charcoal text, orange focus, pink live glow, and medium mint signal.",
            surfaceDeep = Color(0xFFB87B62),
            surfaceBase = Color(0xFFD7A58B),
            surfaceCool = Color(0xFFF0CDBA),
            surfaceAccent = Color(0xFFA56552),
            accent = Color(0xFF8B3419),
            accentLight = Color(0xFF2EAF68),
            accentMuted = Color(0x668B3419),
            panelScrim = Color(0xCC211612),
            osdScrim = Color(0x99211612),
            nowLine = Color(0xFFB5265E),
            nowFill = Color(0x338B3419),
            live = Color(0xFFB5265E),
            pipPreviewOutline = Color(0xFF8B3419),
            focusFill = Color(0x408B3419),
            textPrimary = Color(0xFF3B1607),
            textSecondary = Color(0xFF793018),
            textTertiary = Color(0x99793018),
            textDisabled = Color(0x66793018),
            success = Color(0xFF2EAF68),
            warning = Color(0xFF8B3419),
            info = Color(0xFF2EAF68),
            divider = Color(0x22211120),
            outline = Color(0x408B3419),
        )

        /** Afterglow Light 3 — muted mint-gray wash with deep blue controls. */
        val AfterglowLight3 = AppPalette(
            id = "afterglow_light_3",
            displayName = "Afterglow Light 3",
            description = "Muted mint-gray panels with deep cobalt controls, coral live glow, and navy text.",
            surfaceDeep = Color(0xFFA9C4B2),
            surfaceBase = Color(0xFFC8DBC9),
            surfaceCool = Color(0xFFE6F0E8),
            surfaceAccent = Color(0xFF88A895),
            accent = Color(0xFF173B7A),
            accentLight = Color(0xFF355BCF),
            accentMuted = Color(0x66173B7A),
            panelScrim = Color(0xCC102B27),
            osdScrim = Color(0x99102B27),
            nowLine = Color(0xFFD43D7A),
            nowFill = Color(0x33173B7A),
            live = Color(0xFFD43D7A),
            pipPreviewOutline = Color(0xFF173B7A),
            focusFill = Color(0x40173B7A),
            textPrimary = Color(0xFF111B3D),
            textSecondary = Color(0xFF303B60),
            textTertiary = Color(0x99303B60),
            textDisabled = Color(0x66303B60),
            success = Color(0xFF173B7A),
            warning = Color(0xFF7E3B18),
            info = Color(0xFF355BCF),
            divider = Color(0x22102B27),
            outline = Color(0x40173B7A),
        )

        /** Rachel's Sunrise — daylight version of the mint, powder blue, violet, peach, and pink reference. */
        val RachelsSunrise = AppPalette(
            id = "rachels_sunrise",
            displayName = "Rachel's Sunrise",
            description = "I love you Rachel! Washy sunrise blend of neon peach, orange, pink, mint teal, powder blue, and violet.",
            surfaceDeep = Color(0xFFFFAD4F),
            surfaceBase = Color(0xFFFFD8B8),
            surfaceCool = Color(0xFFFF78B0),
            surfaceAccent = Color(0xFF8AF0E0),
            accent = Color(0xFF211438),
            accentLight = Color(0xFF3A2375),
            accentMuted = Color(0x66211438),
            panelScrim = Color(0xCC211438),
            osdScrim = Color(0x99211438),
            nowLine = Color(0xFF243E88),
            nowFill = Color(0x33211438),
            live = Color(0xFF243E88),
            pipPreviewOutline = Color(0xFF211438),
            focusFill = Color(0x40211438),
            textPrimary = Color(0xFF211438),
            textSecondary = Color(0xFF3D3354),
            textTertiary = Color(0xFF5B526D),
            textDisabled = Color(0x663D3354),
            success = Color(0xFF243E88),
            warning = Color(0xFF6E3D00),
            info = Color(0xFF263D7E),
            divider = Color(0x22211438),
            outline = Color(0x66211438),
            glowIntensity = 1f,
        )

        /** Afterglow Light 4 — warm ash, peach controls, medium mint secondary. */
        val AfterglowLight4 = AppPalette(
            id = "afterglow_light_4",
            displayName = "Afterglow Light 4",
            description = "Warm ash panels with burnt peach focus, medium mint signal, and charcoal contrast.",
            surfaceDeep = Color(0xFFBFA9A0),
            surfaceBase = Color(0xFFDCC5BA),
            surfaceCool = Color(0xFFF0E0D8),
            surfaceAccent = Color(0xFFAD8374),
            accent = Color(0xFF8F3518),
            accentLight = Color(0xFF2EAF68),
            accentMuted = Color(0x668F3518),
            panelScrim = Color(0xCC211816),
            osdScrim = Color(0x99211816),
            nowLine = Color(0xFFA6225A),
            nowFill = Color(0x338F3518),
            live = Color(0xFFA6225A),
            pipPreviewOutline = Color(0xFF2EAF68),
            focusFill = Color(0x408F3518),
            textPrimary = Color(0xFF2E2013),
            textSecondary = Color(0xFF69502A),
            textTertiary = Color(0x9969502A),
            textDisabled = Color(0x6669502A),
            success = Color(0xFF2EAF68),
            warning = Color(0xFF8F3518),
            info = Color(0xFFE7357A),
            divider = Color(0x221C0D1B),
            outline = Color(0x402EAF68),
        )

        /** Afterglow Violet Spectrum — theme built from the six-swatch reference image. */
        val UltravioletSpectrum = AppPalette(
            id = "ultraviolet_spectrum",
            displayName = "Afterglow Violet Spectrum",
            description = "Afterglow six-swatch purple spectrum with lavender highlights and deep violet surfaces.",
            surfaceDeep = Color(0xFF10002B),
            surfaceBase = Color(0xFF240046),
            surfaceCool = Color(0xFF3C096C),
            surfaceAccent = Color(0xFF501488),
            accent = Color(0xFFA855F0),
            accentLight = Color(0xFFE0AAFF),
            accentMuted = Color(0x66A855F0),
            panelScrim = Color(0xD610002B),
            osdScrim = Color(0xA610002B),
            nowLine = Color(0xFFC77DFF),
            nowFill = Color(0x33A855F0),
            live = Color(0xFF9D4EDD),
            pipPreviewOutline = Color(0xFFA855F0),
            focusFill = Color(0x40A855F0),
            textPrimary = Color(0xFFF8F5FF),
            textSecondary = Color(0xD9E0AAFF),
            textTertiary = Color(0x99E0AAFF),
            textDisabled = Color(0x66E0AAFF),
            success = Color(0xFFC77DFF),
            warning = Color(0xFFE0AAFF),
            info = Color(0xFFE0AAFF),
            divider = Color(0x22E0AAFF),
            outline = Color(0x66A855F0),
        )

        /** Mineral Slate — coherent cool blue-slate ramp lit by a single warm copper accent. */
        val MineralSlate = AppPalette(
            id = "mineral_slate",
            displayName = "Mineral Slate",
            description = "Cool blue-slate surfaces stepping dark to light, lit by a single warm copper accent and bronze live marker.",
            surfaceDeep = Color(0xFF0D151D),
            surfaceBase = Color(0xFF1E3142),
            surfaceCool = Color(0xFF40515F),
            surfaceAccent = Color(0xFF5A6A78),
            accent = Color(0xFFFFE6CC),
            accentLight = Color(0xFFFFF1E6),
            accentMuted = Color(0x66FFE6CC),
            panelScrim = Color(0xD613181D),
            osdScrim = Color(0xA613181D),
            nowLine = Color(0xFFDA9D62),
            nowFill = Color(0x33CD8B58),
            live = Color(0xFFDA9D62),
            pipPreviewOutline = Color(0xFFE7B68E),
            focusFill = Color(0x40CD8B58),
            textPrimary = Color(0xFFF4F7F9),
            textSecondary = Color(0xFFC8D0D8),
            textTertiary = Color(0xFF98A4AE),
            textDisabled = Color(0x66C8D0D8),
            success = Color(0xFF82B58C),
            warning = Color(0xFFDA9D62),
            info = Color(0xFFB4C6D6),
            divider = Color(0x22F4F7F9),
            outline = Color(0x66CD8B58),
            glowIntensity = 0.35f,
        )

        /** Afterglow Copper Fjord — theme built from the rust, teal, burgundy, and charcoal swatch reference image. */
        val CopperFjord = AppPalette(
            id = "copper_fjord",
            displayName = "Afterglow Copper Fjord",
            description = "Afterglow rust copper, deep teal, burgundy shadow, and near-black charcoal.",
            surfaceDeep = Color(0xFF071118),
            surfaceBase = Color(0xFF003A40),
            surfaceCool = Color(0xFF003A45),
            surfaceAccent = Color(0xFF015468),
            accent = Color(0xFFD86A3C),
            accentLight = Color(0xFFD46A4E),
            accentMuted = Color(0x66D86A3C),
            panelScrim = Color(0xD6071118),
            osdScrim = Color(0xA6071118),
            nowLine = Color(0xFFD46A4E),
            nowFill = Color(0x33D86A3C),
            live = Color(0xFFD46A4E),
            pipPreviewOutline = Color(0xFF015468),
            focusFill = Color(0x40D86A3C),
            textPrimary = Color(0xFFF7EFEB),
            textSecondary = Color(0xD9D6E6E7),
            textTertiary = Color(0x99D6E6E7),
            textDisabled = Color(0x66D6E6E7),
            success = Color(0xFF2F8AA0),
            warning = Color(0xFFD46A4E),
            info = Color(0xFFB86A78),
            divider = Color(0x22D6E6E7),
            outline = Color(0x66015468),
        )

        /** Afterglow Amber Noir — theme built from the tan, amber, mauve, umber, and black swatch reference image. */
        val AmberNoir = AppPalette(
            id = "amber_noir",
            displayName = "Afterglow Amber Noir",
            description = "Afterglow soft tan, amber gold, muted mauve, umber brown, and near-black.",
            surfaceDeep = Color(0xFF0B0A0C),
            surfaceBase = Color(0xFF2F1E16),
            surfaceCool = Color(0xFF6E585E),
            surfaceAccent = Color(0xFF6B4716),
            accent = Color(0xFFBF8737),
            accentLight = Color(0xFFD0B99A),
            accentMuted = Color(0x66BF8737),
            panelScrim = Color(0xD60B0A0C),
            osdScrim = Color(0xA60B0A0C),
            nowLine = Color(0xFFD0B99A),
            nowFill = Color(0x33BF8737),
            live = Color(0xFFD0B99A),
            pipPreviewOutline = Color(0xFFBF8737),
            focusFill = Color(0x40BF8737),
            textPrimary = Color(0xFFF7EFE5),
            textSecondary = Color(0xD9E7D7C6),
            textTertiary = Color(0x99E7D7C6),
            textDisabled = Color(0x66E7D7C6),
            success = Color(0xFF8C6B74),
            warning = Color(0xFFBF8737),
            info = Color(0xFFD0B99A),
            divider = Color(0x22E7D7C6),
            outline = Color(0x66D0B99A),
        )

        /** Golden Slate — theme built from the navy, steel, cream, sand, and copper swatch reference image. */
        val GoldenSlate = AppPalette(
            id = "golden_slate",
            displayName = "Golden Slate",
            description = "Navy slate, steel blue, soft cream, sand, and copper.",
            surfaceDeep = Color(0xFF182B44),
            surfaceBase = Color(0xFF304A68),
            surfaceCool = Color(0xFF66727B),
            surfaceAccent = Color(0xFF8D755F),
            accent = Color(0xFFDE9040),
            accentLight = Color(0xFFFEEECD),
            accentMuted = Color(0x66DE9040),
            panelScrim = Color(0xD62E3D50),
            osdScrim = Color(0xA62E3D50),
            nowLine = Color(0xFFD7B791),
            nowFill = Color(0x33DE9040),
            live = Color(0xFFDE9040),
            pipPreviewOutline = Color(0xFFD7B791),
            focusFill = Color(0x40DE9040),
            textPrimary = Color(0xFFFEEECD),
            textSecondary = Color(0xFFF1E6CE),
            textTertiary = Color(0xFFD9C9AC),
            textDisabled = Color(0x66E7D9C0),
            success = Color(0xFF8894A2),
            warning = Color(0xFFD7B791),
            info = Color(0xFFFEEECD),
            divider = Color(0x22FEEECD),
            outline = Color(0x66D7B791),
            glowIntensity = 0.35f,
        )

        /** All available presets, alphabetized by display name for theme picker browsing. */
        val ALL: List<AppPalette> = listOf(
            AmberNoir,            // Afterglow Amber Noir
            CopperFjord,          // Afterglow Copper Fjord
            Afterglow1,           // Afterglow Dark 1
            AfterglowSunset,      // Afterglow Dark 2 — default
            Afterglow3,           // Afterglow Dark 3
            Afterglow4,           // Afterglow Dark 4
            AfterglowGray,        // Afterglow Gray (dark monochrome)
            AfterglowGrayLight,
            AfterglowLabs,
            AfterglowLight1,
            AfterglowLight2,
            AfterglowLight3,
            AfterglowLight4,
            UltravioletSpectrum,  // Afterglow Violet Spectrum
            AutumnFall,
            BlueSteel,
            BurningSky,
            CityAfterglow,
            ClassicBlue,
            Earthy,
            ForestMist,
            GoldenSlate,
            GoldenOcean,
            Joyful,
            MineralSlate,
            MountainAfterglow,
            MysteriousLuxury,
            NeonDusk,
            NeonForest,
            NordicCalm,
            PureOnyx,
            RachelsSunrise,       // Rachel's Sunrise
            RedOrangeSky,
            RedSkyMorning,
            SeaHorizon,
            SkinTone,
            SolarAfterglow,
            SunsetAurora,         // Rachel's Sunset
            Synthwave,
            TokyoSunset,
            Vaporwave,
            WindfarmSunset,
        )

        fun byId(id: String?): AppPalette = ALL.firstOrNull { it.id == id } ?: AfterglowSunset
    }
}
